services:
  - type: web
    name: api
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    envVars:
      - key: ZOHO_ACCESS_TOKEN
        sync: false
      - key: ZOHO_CLIENT_ID
        sync: false
      - key: ZOHO_CLIENT_SECRET
        sync: false
      - key: ZOHO_REFRESH_TOKEN
        sync: false
      - key: ZOHO_REDIRECT_URI
        value: https://crm.zoho.com/
      - key: ZOHO_ACCOUNTS_URL
        value: https://accounts.zoho.com
      - key: ZOHO_API_DOMAIN
        value: https://www.zohoapis.com
      - key: ZOHO_CRM_DOMAIN
        value: https://crm.zoho.com
